version: '3.4'

volumes:
  bds:
    external: true

#networks:
#  static-network:
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16



services:

  bds1:

    container_name: emer

    image: itzg/minecraft-bedrock-server
    environment:
      SERVER_NAME: "EmerLand"
      LEVEL_NAME: "EmerLand"
      # LEVEL_NAME: "hunted desert town"
      MAX_PLAYERS: 20
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      ALLOW_CHEATS: "true"
      LEVEL_SEED: "720057903"
      WHITE_LIST: "true"
    ports:
      - 19132:19132/udp
      - 39132:39132
      - 39132:39132/udp
      - 39133:39133
      - 39133:39133/udp
    expose:
      - 19132/udp
    sysctls:
      net.ipv4.ip_local_port_range: 39132 39133
    volumes:
      - bds:/data
    stdin_open: true
    tty: true
    restart: unless-stopped


#  bds2:
#
#    container_name: survival
#
#    image: itzg/minecraft-bedrock-server
#    environment:
#      SERVER_NAME: "blokkY2"
#      LEVEL_NAME: "Survive the night"
#      MAX_PLAYERS: 5
#      EULA: "TRUE"
#      GAMEMODE: creative
#      DIFFICULTY: normal
#      ALLOW_CHEATS: "true"
#      SERVER_PORT: 19140
#    ports:
#      - 19140:19140/udp
#      - 39140:39140
#      - 39140:39140/udp
#      - 39141:39141
#      - 39141:39141/udp
#    expose:
#      - 19140/udp
#    sysctls:
#      net.ipv4.ip_local_port_range: 39140 39141
#    volumes:
#      - bds:/data
#    stdin_open: true
#    tty: true
#    restart: unless-stopped


